import type { historyT } from "./historyType";

export function generateFakeHistory(): historyT[] {
  return [
    {
      gameId: 42,
      date: "08.09.2025 - 17h53",
      points: 69,
      winned: true,
      timePlayed: "38min",
      nbPlayers: 5,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Poppy la mascotte",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 21,
      date: "03.02.2026 - 13h19",
      points: 266,
      winned: false,
      timePlayed: "102min",
      nbPlayers: 3,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 8,
      date: "23.01.2027 - 08h21",
      points: 612,
      winned: false,
      timePlayed: "12min",
      nbPlayers: 4,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 4242,
      date: "18.12.2025 - 19h59",
      points: 88,
      winned: true,
      timePlayed: "28min",
      nbPlayers: 5,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Poppy la mascotte",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 69,
      date: "01.01.2001 - 13h13",
      points: 102,
      winned: true,
      timePlayed: "72min",
      nbPlayers: 7,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Poppy la mascotte",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Frisbee le frisbee",
          mail: "frisbee@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Pas d'inspi le pas d'inspi",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 4,
      date: "02.04.2026 - 15h23",
      points: 0,
      winned: true,
      timePlayed: "300min",
      nbPlayers: 8,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Poppy la mascotte",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Frisbee le frisbee",
          mail: "frisbee@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Pas d'inspi le pas d'inspi",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Che Guevara",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 23,
      date: "06.03.2026 - 11h21",
      points: 99,
      winned: false,
      timePlayed: "12min",
      nbPlayers: 5,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Che Guevara",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 24,
      date: "03.01.2066 - 12h42",
      points: 6666,
      winned: false,
      timePlayed: "666min",
      nbPlayers: 4,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 666,
      date: "06.02.2016 - 14h19",
      points: 66,
      winned: true,
      timePlayed: "63min",
      nbPlayers: 4,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Anouar le bourgeois",
          mail: "anouar@leBourgeois.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 632,
      date: "08.04.2019 - 18h11",
      points: 27,
      winned: true,
      timePlayed: "20min",
      nbPlayers: 4,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Cyril le mousseux",
          mail: "Cyril@leMousseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 420,
      date: "01.01.2001 - 13h13",
      points: 33,
      winned: false,
      timePlayed: "72min",
      nbPlayers: 3,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Pas d'inspi le pas d'inspi",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 25,
      date: "01.01.2001 - 13h13",
      points: 90,
      winned: true,
      timePlayed: "72min",
      nbPlayers: 3,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Pas d'inspi le pas d'inspi",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
    {
      gameId: 33,
      date: "01.01.2002 - 13h14",
      points: 420,
      winned: false,
      timePlayed: "74min",
      nbPlayers: 3,
      players: [
        {
          username: "Dana la violente",
          mail: "dana@laviolente.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Kilian le JSON",
          mail: "kilian@leMouseux.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
        {
          username: "Pas d'inspi le pas d'inspi",
          mail: "poppy@laMascotte.com",
          password: "*****",
          avatar: "beautiful",
          date_joined: "adasd",
          last_login: "d",
          is_online: false,
        },
      ],
    },
  ];
}
