# Generated by Django 6.0.4 on 2026-07-13 11:48

import django.db.models.deletion
import game.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('game', '0001_initial'), ('game', '0002_remove_playerpresence_is_in_game_and_more'), ('game', '0003_rename_channel_name_playerpresence_channelname_and_more'), ('game', '0004_rename_channelname_playerpresence_channel_name_and_more'), ('game', '0005_alter_stat_tricks'), ('game', '0006_room_nb_player'), ('game', '0007_playerpresence_difficulty_room_ended_at_and_more'), ('game', '0008_room_is_private')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('game_state', models.JSONField(default=game.models.default_state)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('open', 'Open'), ('start', 'Start'), ('end', 'End')], default='open', max_length=5)),
                ('nb_player', models.IntegerField(default=0)),
                ('ended_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.room')),
                ('rank', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('player', 'room')},
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('nb_taken', models.IntegerField(default=0)),
                ('nb_last_take', models.IntegerField(default=0)),
                ('nb_trick_choose', models.IntegerField(default=0)),
                ('prefered_trick', models.CharField(choices=[('null', 'Null'), ('club', 'Club'), ('heart', 'Heart'), ('spade', 'Spade'), ('diamond', 'Diamond')], default='null', max_length=10)),
                ('tricks', models.JSONField(default=game.models.tricks_state)),
                ('hand_meld_points', models.IntegerField(default=0)),
                ('board_meld_points', models.IntegerField(default=0)),
                ('highest_hand_meld', models.IntegerField(default=0)),
                ('highest_board_meld', models.IntegerField(default=0)),
                ('nb_host', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='game.room')),
                ('is_human', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6)),
            ],
            options={
                'unique_together': {('player', 'room')},
            },
        ),
    ]
