# Generated by Django 6.0.4 on 2026-04-30 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpresence',
            name='is_in_game',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_started',
        ),
        migrations.AddField(
            model_name='playerpresence',
            name='is_human',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('start', 'Start'), ('end', 'End')], default='open', max_length=5),
        ),
    ]
