# Generated by Django 6.0.4 on 2026-04-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_playerpresence_is_in_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerpresence',
            old_name='channel_name',
            new_name='channelName',
        ),
        migrations.RenameField(
            model_name='playerpresence',
            old_name='is_human',
            new_name='isHuman',
        ),
        migrations.RenameField(
            model_name='playerpresence',
            old_name='is_online',
            new_name='isOnline',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='game_state',
            new_name='gameState',
        ),
    ]
