# Generated by Django 6.0.4 on 2026-04-30 08:58

import django.db.models.deletion
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_channel_name_playerpresence_channelname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerpresence',
            old_name='channelName',
            new_name='channel_name',
        ),
        migrations.RenameField(
            model_name='playerpresence',
            old_name='isHuman',
            new_name='is_human',
        ),
        migrations.RenameField(
            model_name='playerpresence',
            old_name='isOnline',
            new_name='is_online',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='gameState',
            new_name='game_state',
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('nb_taken', models.IntegerField(default=0)),
                ('nb_last_take', models.IntegerField(default=0)),
                ('nb_trick_choose', models.IntegerField(default=0)),
                ('prefered_trick', models.CharField(choices=[('null', 'Null'), ('club', 'Club'), ('heart', 'Heart'), ('spade', 'Spade'), ('diamond', 'Diamond')], default='null', max_length=10)),
                ('tricks', models.JSONField(default=game.models.default_state)),
                ('hand_meld_points', models.IntegerField(default=0)),
                ('board_meld_points', models.IntegerField(default=0)),
                ('highest_hand_meld', models.IntegerField(default=0)),
                ('highest_board_meld', models.IntegerField(default=0)),
                ('nb_host', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
