# Generated by Django 6.0.4 on 2026-04-30 09:44

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_channelname_playerpresence_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='tricks',
            field=models.JSONField(default=game.models.tricks_state),
        ),
    ]
