# Generated by Django 6.0.4 on 2026-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_stat_tricks'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='nb_player',
            field=models.IntegerField(default=0),
        ),
    ]
