# Generated by Django 6.0.4 on 2026-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room_nb_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpresence',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
