# Generated by Django 6.0.4 on 2026-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_room_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_player',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('open', 'Open'), ('start', 'Start'), ('end', 'End')], default='created', max_length=7),
        ),
    ]
