# Generated by Django 6.0.4 on 2026-07-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('game', '0009_room_max_player_alter_room_status'), ('game', '0010_gamelog'), ('game', '0011_alter_gamelog_unique_together_gamelog_game'), ('game', '0012_remove_room_is_private_room_type'), ('game', '0013_alter_room_max_player'), ('game', '0014_alter_room_max_player_alter_room_status'), ('game', '0015_rename_meld_gamelog_score'), ('game', '0016_alter_gamelog_player_alter_playerpresence_player_and_more'), ('game', '0017_room_delete_scheduled_room_host_change_scheduled'), ('game', '0018_room_cleanup_scheduled'), ('game', '0019_playerpresence_is_afk_playerpresence_is_afk_count'), ('game', '0020_room_round_time'), ('game', '0021_alter_gamelog_player'), ('game', '0022_room_goal_room_nb_game_room_nb_point'), ('game', '0023_alter_playerscore_player'), ('game', '0024_room_wait_schedule')]

    dependencies = [
        ('game', '0008_room_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_player',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('start', 'Start'), ('end', 'End')], default='open', max_length=5),
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_private',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends_only'), ('private', 'Private')], default='private', max_length=12),
        ),
        migrations.AlterField(
            model_name='playerpresence',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='delete_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='host_change_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='cleanup_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerpresence',
            name='is_afk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerpresence',
            name='is_afk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='round_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerP', to='game.playerpresence')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.room')),
                ('game', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.AddField(
            model_name='room',
            name='goal',
            field=models.CharField(choices=[('games', 'Games'), ('points', 'Points')], default='games', max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='nb_games',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='nb_points',
            field=models.IntegerField(default=333),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_presence', to='game.playerpresence'),
        ),
        migrations.AddField(
            model_name='room',
            name='wait_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
