# Generated by Django 6.0.4 on 2026-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gamelog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='game',
            field=models.IntegerField(default=0),
        ),
    ]
