# Generated by Django 6.0.4 on 2026-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gamelog_unique_together_gamelog_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_private',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends_only'), ('private', 'Private')], default='private', max_length=12),
        ),
    ]
