# Generated by Django 6.0.4 on 2026-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_room_is_private_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_player',
            field=models.IntegerField(default=1),
        ),
    ]
