# Generated by Django 6.0.4 on 2026-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_room_max_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_player',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('start', 'Start'), ('end', 'End')], default='open', max_length=5),
        ),
    ]
