# Generated by Django 6.0.4 on 2026-06-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_room_max_player_alter_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='meld',
            new_name='score',
        ),
    ]
