# Generated by Django 6.0.4 on 2026-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_room_delete_scheduled_room_host_change_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleanup_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
