# Generated by Django 6.0.4 on 2026-06-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_room_cleanup_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpresence',
            name='is_afk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerpresence',
            name='is_afk_count',
            field=models.IntegerField(default=0),
        ),
    ]
