# Generated by Django 6.0.4 on 2026-06-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_playerpresence_is_afk_playerpresence_is_afk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
