# Generated by Django 6.0.4 on 2026-06-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_room_round_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerP', to='game.playerpresence'),
        ),
    ]
