# Generated by Django 6.0.4 on 2026-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_gamelog_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='goal',
            field=models.CharField(choices=[('games', 'Games'), ('points', 'Points')], default='games', max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='nb_games',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='nb_points',
            field=models.IntegerField(default=333),
        ),
    ]
