# Generated by Django 6.0.4 on 2026-06-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_room_goal_room_nb_game_room_nb_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_presence', to='game.playerpresence'),
        ),
    ]
