# Generated by Django 6.0.4 on 2026-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_playerscore_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='wait_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
