# Generated by Django 6.0.4 on 2026-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_room_wait_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
