# Generated by Django 6.0.4 on 2026-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('game', '0025_room_is_paused'), ('game', '0026_playerpresence_disconnected_scheduled')]

    dependencies = [
        ('game', '0024_room_wait_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerpresence',
            name='disconnected_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
