# Generated by Django 6.0.4 on 2026-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_room_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpresence',
            name='disconnected_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
