# Generated by Django 6.0.4 on 2026-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_playerpresence_disconnected_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpresence',
            name='ban_vote',
            field=models.IntegerField(default=0),
        ),
    ]
