# Generated by Django 6.0.4 on 2026-07-07 10:48

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_playerpresence_ban_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpresence',
            name='ban_vote',
        ),
        migrations.AddField(
            model_name='room',
            name='ban',
            field=models.JSONField(default=game.models.default_state),
        ),
    ]
