# Generated by Django 6.0.4 on 2026-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_stat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='play_card',
            field=models.BooleanField(default=False),
        ),
    ]
