# Generated by Django 6.0.4 on 2026-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_room_play_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_collation='utf8_bin', max_length=8, unique=True),
        ),
    ]
