# Generated by Django 6.0.4 on 2026-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('start', 'Start'), ('end', 'End'), ('abandoned', 'Abandoned')], default='open', max_length=9),
        ),
    ]
