# Generated by Django 6.0.4 on 2026-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_online_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=0),
        ),
    ]
