# Generated by Django 6.0.4 on 2026-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
