# Generated by Django 6.0.4 on 2026-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friendship_accepted_at_alter_friendship_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='avatars/avatar.jpg', max_length=255),
        ),
    ]
