# Generated by Django 6.0.4 on 2026-05-12 07:56

from django.db import migrations
from django.contrib.auth.hashers import make_password
#TODO delete that at the end
def create_users(apps, schema_editor):
    User = apps.get_model("api", "User")
    Stat = apps.get_model("game", "Stat")

    users = [
        {
            "username": "cyril",
            "email": "cyril@test.com",
        },
        {
            "username": "dana",
            "email": "dana@test.com",
        },
        {
            "username": "alex",
            "email": "alex@test.com",
        },
        {
            "username": "kiki",
            "email": "kiki@test.com",
        },
        {
            "username": "anouar",
            "email": "anouar@test.com",
        }
    ]

    for data in users:

        if not User.objects.filter(username=data["username"]).exists():

            user = User.objects.create(
                username=data["username"],
                email=data["email"],
                password=make_password("password123"),
                avatar="avatars/avatar.jpg",
                is_online=False,
            )

            Stat.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20260512_0755'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
