# Generated by Django 6.0.4 on 2026-05-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='blocked_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
