# Generated by Django 6.0.4 on 2026-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fortytwo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='has_password',
            field=models.BooleanField(default=True),
        ),
    ]
