# Generated by Django 6.0.4 on 2026-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_fortytwo_id_user_github_id_user_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fortytwo_id',
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(default="", max_length=255),
        ),
    ]
