# Generated by Django 6.0.4 on 2026-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0013_user_presence'), ('api', '0014_user_presence_game'), ('api', '0015_alter_user_username')]

    dependencies = [
        ('api', '0012_alter_user_fortytwo_id_alter_user_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='presence_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
