# Generated by Django 6.0.4 on 2026-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_fortytwo_id_alter_user_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence',
            field=models.IntegerField(default=0),
        ),
    ]
