# Generated by Django 6.0.4 on 2026-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence_game',
            field=models.IntegerField(default=0),
        ),
    ]
