# Generated by Django 6.0.4 on 2026-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clovers',
            field=models.IntegerField(default=0),
        ),
    ]
