# Generated by Django 6.0.4 on 2026-07-09 16:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_clovers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition',
            field=models.JSONField(default=api.models.default_condition),
        ),
    ]
