# Generated by Django 6.0.4 on 2026-07-08 14:29

from django.db import migrations

def create_achievements(apps, schema_editor):
    Achievement = apps.get_model("api", "Achievement")
    
    if not Achievement.objects.filter(code="LUCKY").exists():
        Achievement.objects.create(
            code="LUCKY",
            title="lucky",
            description="You found a four-leaf clover when you arrived",
            condition={
                "source": "user",
                "type": "clovers",
                "operator": ">=",
                "value": 1
            },
            icon="achievements/clover.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="SUPER_LUCKY").exists():
        Achievement.objects.create(
            code="SUPER_LUCKY",
            title="super lucky",
            description="You found three four-leaf clovers when you arrived",
            condition={
                "source": "user",
                "type": "clovers",
                "operator": ">=",
                "value": 3
            },
            icon="achievements/triple_clover.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER_1").exists():
        Achievement.objects.create(
            code="LOSER_1",
            title="loser 1",
            description="reach -10 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": "<=",
                "value": -10
            },
            icon="achievements/loser_1.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="LOSER_2").exists():
        Achievement.objects.create(
            code="LOSER_2",
            title="loser 2",
            description="reach -42 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": "<=",
                "value": -42
            },
            icon="achievements/loser_2.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER_3").exists():
        Achievement.objects.create(
            code="LOSER_3",
            title="loser 3",
            description="reach -67 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": "<=",
                "value": -67
            },
            icon="achievements/loser_3.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER_4").exists():
        Achievement.objects.create(
            code="LOSER_4",
            title="loser 4",
            description="reach -69 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": "<=",
                "value": -69
            },
            icon="achievements/loser_4.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="LOSER_5").exists():
        Achievement.objects.create(
            code="LOSER_5",
            title="loser 5",
            description="reach -420 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": "<=",
                "value": -420
            },
            icon="achievements/loser_5.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WINNER_1").exists():
        Achievement.objects.create(
            code="WINNER_1",
            title="winner 1",
            description="reach 10 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": ">=",
                "value": 10
            },
            icon="achievements/winner_1.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WINNER_2").exists():
        Achievement.objects.create(
            code="WINNER_2",
            title="winner 2",
            description="reach 42 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": ">=",
                "value": 42
            },
            icon="achievements/winner_2.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="WINNER_3").exists():
        Achievement.objects.create(
            code="WINNER_3",
            title="winner 3",
            description="reach 67 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": ">=",
                "value": 67
            },
            icon="achievements/winner_3.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="WINNER_4").exists():
        Achievement.objects.create(
            code="WINNER_4",
            title="winner 4",
            description="reach 69 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": ">=",
                "value": 69
            },
            icon="achievements/winner_4.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WINNER_5").exists():
        Achievement.objects.create(
            code="WINNER_5",
            title="winner 5",
            description="reach 420 elo",
            condition={
                "source": "user",
                "type": "elo",
                "operator": ">=",
                "value": 420
            },
            icon="achievements/winner_5.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="WINNER").exists():
        Achievement.objects.create(
            code="WINNER",
            title="winner",
            description="win a game",
            condition={
                "source": "user",
                "type": "win",
                "operator": ">=",
                "value": 1
            },
            icon="achievements/winner.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="LOSER").exists():
        Achievement.objects.create(
            code="LOSER",
            title="loser",
            description="lost a game",
            condition={
                "source": "user",
                "type": "lose",
                "operator": ">=",
                "value": 1
            },
            icon="achievements/loser.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="DM").exists():
        Achievement.objects.create(
            code="DM",
            title="dungeon master",
            description="host a game",
            condition={
                "source": "user",
                "type": "nb_host",
                "operator": ">=",
                "value": 1
            },
            icon="achievements/dm.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="WELCOME").exists():
        Achievement.objects.create(
            code="WELCOME",
            title="welcome",
            description="create an account",
            condition={
                "source": "user",
                "type": "account_created",
                "operator": ">=",
                "value": 1
            },
            icon="achievements/welcome.jpg",
            is_hidden=False
        )
    
    if not Achievement.objects.filter(code="FRIENDSHIP").exists():
        Achievement.objects.create(
            code="FRIENDSHIP",
            title="friendship",
            description="get a friend",
            condition={
                "source": "user",
                "type": "friends",
                "operator": ">=",
                "value": 1
            },
            icon="achievements/friendship.jpg",
            is_hidden=False
        )
        
    if not Achievement.objects.filter(code="FRIENDSHIP_1").exists():
        Achievement.objects.create(
            code="FRIENDSHIP_1",
            title="friendship_1",
            description="get 5 friends",
            condition={
                "source": "user",
                "type": "friends",
                "operator": ">=",
                "value": 5
            },
            icon="achievements/friendship_1.jpg",
            is_hidden=False
        )
    if not Achievement.objects.filter(code="FRIENDSHIP_2").exists():
        Achievement.objects.create(
            code="FRIENDSHIP_2",
            title="friendship_2",
            description="get 42 friends",
            condition={
                "source": "user",
                "type": "friends",
                "operator": ">=",
                "value": 42
            },
            icon="achievements/friendship_2.jpg",
            is_hidden=False
        )
    
    #if not Achievement.objects.filter(code="SKILL_ISSUE").exists():
    #    Achievement.objects.create(
    #        code="SKILL_ISSUE",
    #        title="skill issue",
    #        description="to have both Buur and Neil on the same game",
    #        condition={
    #            "source": "game",
    #            "type": "buur_and_neil"
    #        },
    #        icon="achievements/skill_issue.jpg",
    #        is_hidden=False
    #    )
        

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_achievement_condition'),
    ]

    operations = [
        migrations.RunPython(create_achievements),
    ]
    

