# Generated by Django 6.0.4 on 2026-08-12 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_emailverification_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
