name: Deploy to VM

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check migrations changes
        id: migrations
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E ".*/migrations/.*\.py$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy with reset
        env:
          APP_DIR: ${{ secrets.VM_APP_DIR }}
        if: steps.migrations.outputs.changed == 'true'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/transcendence/
            #TODO delete git stash and git stash pop
            #TODO change git checkout to main
            git stash
            git fetch origin
            git checkout backend
            git reset --hard origin/backend
            git stash pop

            make fclean
            make serv-build

      - name: Normal deploy
        if: steps.migrations.outputs.changed == 'false'
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_DIR: ${{ secrets.VM_APP_DIR }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/transcendence/
            #TODO delete git stash and git stash pop
            #TODO change git checkout to main

            git stash
            git fetch origin
            git checkout backend
            git reset --hard origin/backend
            git stash pop

            make serv-build